version: '3.3'

services:
  database:
    build:
      context: ..
      dockerfile: multi-tier-app/db/Dockerfile
    container_name: db
    restart: always
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ..
      dockerfile: multi-tier-app/backend/Dockerfile
    container_name: api
    restart: always
    depends_on:
      - database
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./frontend
    container_name: ui
    restart: always
    depends_on:
      - backend
    networks:
      - frontend-network
    ports:
      - "80:80"

networks:
  backend-network:
  frontend-network:

volumes:
  mongo-data:
